{
 "title": "Celery Monitoring",
 "description": "Basic celery monitoring example",
 "tags": [
  "celery",
  "monitoring",
  "flower"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RAM Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Tasks Currently Executing at Worker",
   "type": "graph",
   "description": "This panel shows number of tasks currently executing at worker.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flower_worker_number_of_currently_executing_tasks",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Prefetch Time at Worker",
   "type": "graph",
   "description": "This panel shows task prefetch time at worker by worker and task name.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "flower_task_prefetch_time_seconds",
     "legendFormat": "{{task}}, {{worker}}"
    }
   ]
  },
  {
   "title": "Task Failure Ratio",
   "type": "graph",
   "description": "This panel presents average task failure ratio over time by task name.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(avg_over_time(flower_events_total{type=\"task-failed\"}[15m])) by (task) / sum(avg_over_time(flower_events_total{type=~\"task-failed|task-succeeded\"}[15m])) by (task)) * 100",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "1-min Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Celery Worker Status",
   "type": "graph",
   "description": "This panel shows status of celery workers. 1 = online, 0 = offline.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "flower_worker_online", "legendFormat": "{{ worker }}" }
   ]
  },
  {
   "title": "Average Task Runtime at Worker",
   "type": "graph",
   "description": "This panel shows average task runtime at worker by worker and task name.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(flower_task_runtime_seconds_sum[5m]) / rate(flower_task_runtime_seconds_count[5m])",
     "legendFormat": "{{task}}, {{worker}}"
    }
   ]
  },
  {
   "title": "Number of Tasks Prefetched At Worker",
   "type": "graph",
   "description": "This panel shows number of tasks prefetched at worker by task and worker name.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "flower_worker_prefetched_tasks", "legendFormat": "{{task}}, {{worker}}" }
   ]
  },
  {
   "title": "Task Success Ratio",
   "type": "graph",
   "description": "This panel presents average task success ratio over time by task name.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(avg_over_time(flower_events_total{type=\"task-succeeded\"}[15m])) by (task)  / sum(avg_over_time(flower_events_total{type=~\"task-failed|task-succeeded\"}[15m])) by (task)) * 100",
     "legendFormat": "{{ task }}"
    }
   ]
  }
 ]
}