- name: generate a key
  hosts: host
  tasks:
    - name: generate a key
      include_tasks: ansible_tasks/generate_keys.yaml
  
- name: prepare disk on cluster nodes
  hosts: cluster:client
  tasks:
    - name: distributr keys
      include_tasks: ansible_tasks/distribute_keys.yaml

- name: Install EPEL
  hosts: cluster:client:host
  become: true
  become_user: root
  tasks:
    - name: distributr keys
      include_tasks: ansible_tasks/install_epel.yaml

- name: Gather and Use Cluster IPs
  hosts: cluster:client 
  tasks:
    - name: Create /etc/exports on Ansible Host
      include_tasks: ansible_tasks/nfs-setup_host.yaml

- name: Install and prepare NFS
  hosts: cluster:client:host  
  tasks:
    - name: Install and prepare NFS
      include_tasks: ansible_tasks/nfs-packages.yaml

- name: NFS fstab
  hosts: cluster:client
  become: true
  become_user: root
  tasks:
    - name: NFS fstab
      ansible.posix.mount:
        boot: true
        state: mounted
        fstype: nfs
        src: 10.0.6.234:/home/ec2-user/data/shared
        path: /home/ec2-user/data/shared
        opts: defaults,_netdev
      

- name: Install RabbitMQ
  hosts: client
  become: true
  become_user: root
  tasks:
    - name: Install RabbitMQ
      include_tasks: ansible_tasks/rabbitMQ_server.yaml
    
  handlers:
    - name: restart rabbitmq
      service:
        name: rabbitmq-server
        state: restarted