- name: Initial Configuration
  hosts: coursemachines
  become: true
  become_user: root
  tasks:
  - name: Setup CRB repo
    shell: "subscription-manager config --rhsm.manage_repos=1 && subscription-manager repos --enable codeready-builder-for-rhel-9-x86_64-rpms"
  - name: EPEL Key
    rpm_key:
      state: present
      key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9"
  - name: Add EPEL release
    ansible.builtin.dnf:
      name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
      state: present
  - name: Update packages
    ansible.builtin.dnf:
      name: "*"
      state: latest
  - name: Install g++
    ansible.builtin.dnf:
      name: "g++"
      state: latest
  - name: Install gfortran
    ansible.builtin.dnf:
      name: "gfortran"
      state: latest
  - name: Install openmpi devel 
    ansible.builtin.dnf:
      name: "openmpi-devel"
      state: latest
  - name: Install openmpi
    ansible.builtin.dnf:
      name: "openmpi"
      state: latest
  - name: Install slurm
    ansible.builtin.dnf:
      name: "slurm"
      state: latest
  - name: Install slurm-cltd
    ansible.builtin.dnf:
      name: "slurm-slurmctld"
      state: latest
  - name: Install slurmd
    ansible.builtin.dnf:
      name: "slurm-slurmd"
      state: latest
  - name: Install munge
    ansible.builtin.dnf:
      name: "munge"
      state: latest
  - name: Install patch
    ansible.builtin.dnf:
      name: "patch"
      state: latest
  - name: Install munge
    ansible.builtin.dnf:
      name: "bzip2"
      state: latest
  - name: Install mpi4y
    ansible.builtin.dnf:
      name: "python3-mpi4py-openmpi"
      state: latest
