- hosts: cluster[2]  
  become: yes         
  tasks:
    - name: python
      ansible.builtin.dnf:
        name: 
              - python3
              - python3-pip
              - git

    - name: Create virtual environment directory
      ansible.builtin.file:
        path: /home/ec2-user/data/merizo_venv
        state: directory

    - name: Create virtual environment
      ansible.builtin.command: python3 -m venv /home/ec2-user/data/merizo_venv
    
    - name: Copy requirements.txt to remote machine
      ansible.builtin.copy:
        src: ./merizo_reqs.txt # Local path on control node
        dest: /home/ec2-user/merizo_reqs.txt
    
    - name: Copy example file
      ansible.builtin.copy:
        src: ./AF-A0A0A0MRZ7-F1-model_v4.pdb # Local path on control node
        dest: /home/ec2-user/AF-A0A0A0MRZ7-F1-model_v4.pdb

    - name: Activate virtual environment
      ansible.builtin.shell: source /home/ec2-user/data/merizo_venv/bin/activate

    - name: Install dependencies from requirements.txt
      ansible.builtin.pip:
        requirements: "/home/ec2-user/merizo_reqs.txt"