- name: Create pip cache directory
  become: true
  become_user: root
  ansible.builtin.file:
    path: /home/ec2-user/data/pip_cache
    state: directory
    owner: ec2-user
    group: ec2-user

# - name: Set PIP_CACHE_DIR environment variable
#   become: true
#   become_user: root
#   shell: echo "export $PIP_CACHE_DIR=/home/ec2-user/data/pip_cache" >> /home/ec2-user/.bashrc
- name: make tmpdir for pip on disk
  ansible.builtin.file:
    path: /home/ec2-user/data/tmp
    state: directory
    owner: ec2-user
    group: ec2-user

- name: Copy requirements.txt to remote machine
  ansible.builtin.copy:
    src: ./merizo_reqs.txt # Local path on control node
    dest: /home/ec2-user/data/shared/merizo_reqs.txt

- name: Copy example file
  ansible.builtin.copy:
    src: ./AF-A0A0A0MRZ7-F1-model_v4.pdb # Local path on control node
    dest: /home/ec2-user/data/shared/AF-A0A0A0MRZ7-F1-model_v4.pdb

- name: Activate the virtual environment
  shell: source /home/ec2-user/data/celery_venv/bin/activate

- name: Install Merizo dependencies
  shell: TMPDIR=/home/ec2-user/data/tmp /home/ec2-user/data/celery_venv/bin/pip install -r /home/ec2-user/data/shared/merizo_reqs.txt

# - name: Install dependencies from requirements.txt
#   ansible.builtin.pip:
#     requirements: "/home/ec2-user/merizo_reqs.txt"


#  - name: Create virtual environment directory
#       ansible.builtin.file:
#         path: /home/ec2-user/data/merizo_venv
#         state: directory

#     - name: Create virtual environment
#       ansible.builtin.command: python3 -m venv /home/ec2-user/data/merizo_venv