- name: Install Flask
  shell: /home/ec2-user/data/celery_venv/bin/pip install Flask

- name: copy web_app directory from ansible host to client
  ansible.builtin.copy:
    src: /home/ec2-user/coursework/web_app
    dest: /home/ec2-user/data/
    owner: ec2-user
    group: ec2-user
    